CREATE EXTENSION PG_TRGM;

CREATE TABLE TB_PESSOA (
    ID VARCHAR(36),
    APELIDO VARCHAR(32) CONSTRAINT ID_PK PRIMARY KEY,
    NOME VARCHAR(100),
    NASCIMENTO CHAR(10),
    STACK VARCHAR(1024),
    TERMO_SEARCH TEXT GENERATED ALWAYS AS (NOME || APELIDO || STACK) STORED
);

CREATE INDEX CONCURRENTLY IF NOT EXISTS id_idx ON TB_PESSOA (ID);
CREATE INDEX CONCURRENTLY IF NOT EXISTS termo_idx_tgrm ON TB_PESSOA USING GIST (TERMO_SEARCH GIST_TRGM_OPS(SIGLEN=64));